/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.us.isa.sedl.jlibsedl;

import es.us.isa.sedl.core.ControlledExperiment;
import es.us.isa.sedl.core.EmpiricalStudy;
import es.us.isa.sedl.core.util.Error;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author japarejo
 */
public class SEDLDocument {

    private final static String jlibsedmlVersion = "${version}";
    final static String PROVENANCE = "This file was generated by jLibSEDL, version " + jlibsedmlVersion + ".";
    protected EmpiricalStudy experiment;
    protected List<Error> errors;

    public SEDLDocument(EmpiricalStudy experiment) {
        this(experiment, new ArrayList<Error>());
    }

    public SEDLDocument(EmpiricalStudy experiment, List<Error> errors) {
        //Assert.checkNoNullArgs(experiment, errors);
        this.experiment = experiment;
        this.errors = errors;
    }

    public SEDLDocument() {
        experiment = new ControlledExperiment();
        errors = new ArrayList<Error>();
    }

    public List<Error> getErrors() {
        return Collections.unmodifiableList(errors);
    }

    public EmpiricalStudy getExperiment() {
        return experiment;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SEDLDocument other = (SEDLDocument) obj;
        if (this.experiment != other.experiment && (this.experiment == null || !this.experiment.equals(other.experiment))) {
            return false;
        }
        if (this.errors != other.errors && (this.errors == null || !this.errors.equals(other.errors))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + (this.experiment != null ? this.experiment.hashCode() : 0);
        hash = 97 * hash + (this.errors != null ? this.errors.hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "SEDLDocument{" + "experiment=" + experiment + ", errors=" + errors + '}';
    }
    
    
}
