/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.us.isa.sedl.core.context;

import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author japarejo
 */
public class LibraryOfCongressClassificationSystem extends BiLevelClassificationSystem {
              
    public LibraryOfCongressClassificationSystem()
    {
        this.name="LCC";
        this.url="https://www.loc.gov/catdir/cpso/lcco/";        
        String[][] mainCathegories={            
            {"A","General Works"},
            {"B","Philosophy. Psychology. Religion"},
            {"C","Auxiliary Sciences of History"},
            {"D","World History and History of Europe, Asia, Africa, Australia, New Zealand, etc."},
            {"E","History of the Americas"},
            {"F","History of the Americas"},
            {"G","Geography, Anthropology, and Recreation"},
            {"H","Social Sciences"},
            {"J","Political Science"},
            {"K","Law"},
            {"L","Education"},
            {"M","Music"},
            {"N","Fine Arts"},
            {"P","Language and Literature"},
            {"Q","Science"},
            {"R","Medicine"},
            {"S","Agriculture"},
            {"T","Technology"},
            {"U","Military Science"},
            {"V","Naval Science"},
            {"Z","Bibliography, Library Science, and General Information Resources"}                
        };
        String[][] subclasses={
            {"AC","Collections. Series. Collected works"},
            {"AE","Encyclopedias"},
            {"AG","Dictionaries and other general reference works"},
            {"AI","Indexes"},
            {"AM","Museums. Collectors and collecting"},
            {"AN","Newspapers"},
            {"AP","Periodicals"},
            {"AS","Academies and learned societies"},
            {"AY","Yearbooks. Almanacs. Directories"},
            {"AZ","History of scholarship and learning. The humanities"},
            {"BB","Philosophy (General)"},
            {"BC","Logic"},
            {"BD","Speculative philosophy"},
            {"BF","Psychology"},
            {"BH","Aesthetics"},
            {"BJ","Ethics"},
            {"BL","Religions. Mythology. Rationalism"},
            {"BM","Judaism"},
            {"BP","Islam. Bahaism. Theosophy, etc."},
            {"BQ","Buddhism"},
            {"BR","Christianity"},
            {"BS","The Bible"},
            {"BT","Doctrinal theology"},
            {"BV","Practical Theology"},
            {"BX","Christian Denominations"},
            {"CB","History of Civilization"},
            {"CC","Archaeology"},
            {"CD","Diplomatics. Archives. Seals"},
            {"CE","Technical Chronology. Calendar"},
            {"CJ","Numismatics"},
            {"CN","Inscriptions. Epigraphy"},
            {"CR","Heraldry"},
            {"CS","Genealogy"},
            {"CT","Biography"},
            {"DA","History of Great Britain"},
            {"DAW","History of Central Europe"},
            {"DB","History of Austria,Liechtenstein,Hungary,Czechoslovakia"},
            {"DC","History of France, Andorra, Monaco"},
            {"DD","History of Germany"},
            {"DE","History of Greco-Roman World"},
            {"DF","History of Greece"},
            {"DG","History of Italy,Malta"},
            {"DH","History of Low Countries, Benelux Countries"},
            {"DJ","History of Netherlands (Holland)"},
            {"DJK","History of Eastern Europe (General)"},
            {"DK","History of Russia. Soviet Union. Former Soviet Republics, Poland"},
            {"DL","History of Northern Europe. Scandinavia"},
            {"DP","History of Spain,Portugal"},
            {"DQ","History of Switzerland"},
            {"DR","History of Balkan Peninsula"},
            {"DS","History of Asia"},
            {"DT","History of Africa"},
            {"DU","History of Oceania (South Seas)"},
            {"DX","History of Romanies"},
            {"GA","Mathematical geography. Cartography"},
            {"GB","Physical geography"},
            {"GC","Oceanography"},
            {"GE","Environmental Sciences"},
            {"GF","Human ecology. Anthropogeography"},
            {"GN","Anthropology"},
            {"GR","Folklore"},
            {"GT","Manners and customs (General)"},
            {"GV","Recreation. Leisure"},
            {"HA","Statistics"},
            {"HB","Economic theory. Demography"},
            {"HC","Economic history and conditions"},
            {"HD","Industries. Land use. Labor"},
            {"HE","Transportation and communications"},
            {"HF","Commerce"},
            {"HG","Finance"},
            {"HJ","Public finance"},
            {"HM","Sociology (General)"},
            {"HN","Social history and conditions. Social problems. Social reform"},
            {"HQ","The family. Marriage, Women and Sexuality"},
            {"HS","Societies: secret, benevolent, etc."},
            {"HT","Communities. Classes. Races"},
            {"HV","Social pathology. Social and public welfare. Criminology"},
            {"HX","Socialism. Communism. Anarchism"},
            {"JA","Political science (General)"},
            {"JC","Political theory"},
            {"JF","Political institutions and public administration"},
            {"JJ","Political institutions and public administration (North America)"},
            {"JK","Political institutions and public administration (United States)"},
            {"JL","Political institutions and public administration (Canada, Latin America, etc.)"},
            {"JN","Political institutions and public administration (Europe)"},
            {"JQ","Political institutions and public administration (Asia, Africa, Australia, Pacific Area, etc.)"},
            {"JS","Local government. Municipal government"},
            {"JV","Colonies and colonization. Emigration and immigration. International migration"},
            {"JX","International law, see JZ and KZ (obsolete)"},
            {"JZ","International relations"},
            {"KB","Religious law in general. Comparative religious law. Jurisprudence"},
            {"KBM","Jewish law"},
            {"KBP","Islamic law"},
            {"KBR","History of canon law"},
            {"KBS","Canon law of Eastern churches"},
            {"KBT","Canon law of Eastern Rite Churches in Communion with the Holy See of Rome"},
            {"KBU","Law of the Roman Catholic Church. The Holy See"},
            {"KD/KDK","United Kingdom and Ireland"},
            {"KDZ","America. North America"},
            {"KE","Canada"},
            {"KF","United States"},
            {"KG","Latin America","Mexico and Central America","West Indies. Caribbean area"},
            {"KH","South America"},
            {"KJ-KKZ","Europe"},
            {"KL-KWX","Asia and Eurasia, Africa, Pacific Area, and Antarctica"},
            {"KU","Law of Australia and New Zealand"},
            {"KZ","Law of nations"},
            {"LA","History of education"},
            {"LB","Theory and practice of education"},
            {"LC","Special aspects of education"},
            {"LD","Individual institutions-United States"},
            {"LE","Individual institutions-America (except United States)"},
            {"LF","Individual institutions-Europe"},
            {"LG","Individual institutions-Asia, Africa, Indian Ocean islands, Australia, New Zealand, Pacific islands"},
            {"LH","College and school magazines and papers"},
            {"LJ","Student fraternities and societies, United States"},
            {"LT","Textbooks"},
            {"ML","Literature on music"},
            {"MT","Instruction and study of music"},
            {"NA","Architecture"},
            {"NB","Sculpture"},
            {"NC","Drawing. Design. Illustration"},
            {"ND","Painting"},
            {"NE","Print media"},
            {"NK","Decorative arts"},
            {"NX","Arts in general"},
            {"PA","Greek language and literature. Latin language and literature"},
            {"PB","Modern languages. Celtic languages and literature"},
            {"PC","Romanic languages"},
            {"PD","Germanic languages. Scandinavian languages"},
            {"PE","English language"},
            {"PF","West Germanic languages"},
            {"PG","Slavic languages and literatures. Baltic languages. Albanian language"},
            {"PH","Uralic languages. Basque language"},
            {"PJ","Oriental languages and literatures"},
            {"PK","Indo-Iranian languages and literatures"},
            {"PL","Languages and literatures of Eastern Asia, Africa, Oceania"},
            {"PM","Hyperborean, Native American, and artificial languages"},
            {"PN","Literature (General)"},
            {"PQ","French literature,Italian literature,Spanish literature,Portuguese literature"},
            {"PR","English literature"},
            {"PS","American literature"},
            {"PT","German literature","Dutch literature,Flemish literature since 1830,Afrikaans literature,Scandinavian literature,Old Norse literature: Old Icelandic and Old Norwegian,Modern Icelandic literature,Faroese literature,Danish literature,Norwegian literature,Swedish literature"},
            {"PZ","Fiction and juvenile belles lettres"},
            {"QA","Mathematics"},
            {"QB","Astronomy"},
            {"QC","Physics"},
            {"QD","Chemistry"},
            {"QE","Geology"},
            {"QH","Natural history,Biology"},
            {"QK","Botany"},
            {"QL","Zoology"},
            {"QM","Human anatomy"},
            {"QP","Physiology"},
            {"QR","Microbiology"},
            {"RA","Public aspects of medicine"},
            {"RB","Pathology"},
            {"RC","Internal medicine"},
            {"RD","Surgery"},
            {"RE","Ophthalmology"},
            {"RF","Otorhinolaryngology"},
            {"RG","Gynecology and Obstetrics"},
            {"RJ","Pediatrics"},
            {"RK","Dentistry"},
            {"RL","Dermatology"},
            {"RM","Therapeutics. Pharmacology"},
            {"RS","Pharmacy and materia medica"},
            {"RT","Nursing"},
            {"RV","Botanic, Thomsonian, and Eclectic medicine"},
            {"RX","Homeopathy"},
            {"RZ","Other systems of medicine"},
            {"SB","Horticulture. Plant propagation. Plant breeding"},
            {"SD","Forestry. Arboriculture. Silviculture"},
            {"SF","Animal husbandry. Animal science"},
            {"SH","Aquaculture. Fisheries. Angling"},
            {"SK","Hunting"},
            {"TA","Engineering Civil engineering (General)."},
            {"TC","Hydraulic engineering. Ocean engineering"},
            {"TD","Environmental technology. Sanitary engineering"},
            {"TE","Highway engineering. Roads and pavements"},
            {"TF","Railroad engineering and operation"},
            {"TG","Bridges"},
            {"TH","Building construction"},
            {"TJ","Mechanical engineering and machinery"},
            {"TK","Electrical engineering. Electronics. Nuclear engineering"},
            {"TL","Motor vehicles. Aeronautics. Astronautics"},
            {"TN","Mining engineering. Metallurgy"},
            {"TP","Chemical technology"},
            {"TR","Photography"},
            {"TS","Manufacturing engineering. Mass production"},
            {"TT","Handicrafts. Arts and crafts"},
            {"TX","Home economics (Technology)"},
            {"UA","Armies: Organization, distribution, military situation"},
            {"UB","Military administration"},
            {"UC","Military maintenance and transportation"},
            {"UD","Infantry"},
            {"UE","Cavalry. Armor"},
            {"UF","Artillery"},
            {"UG","Military engineering. Air forces"},
            {"UH","Other military services"},
            {"VA","Navies: Organization, distribution, naval situation"},
            {"VB","Naval administration"},
            {"VC","Naval maintenance"},
            {"VD","Naval seamen"},
            {"VE","Marines"},
            {"VF","Naval ordnance"},
            {"VG","Minor services of navies"},
            {"VK","Navigation. Merchant marine"},
            {"VM","Naval architecture. Shipbuilding. Marine engineering"},
            {"ZA","Information resources/materials"}};            
        init(mainCathegories,subclasses);
    }
    
    @Override
    public Object createNewInstance() {
        return new LibraryOfCongressClassificationSystem();
    }    
        
}
